/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.2
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGD


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdlib.h>
#include <string.h>
#include <stdio.h>


// Support for throwing D exceptions from C/C++.
typedef enum {
  SWIG_DException = 0,
  SWIG_DIllegalArgumentException,
  SWIG_DIllegalElementException,
  SWIG_DIOException,
  SWIG_DNoSuchElementException,
} SWIG_DExceptionCodes;

typedef void (* SWIG_DExceptionCallback_t)(const char *);

typedef struct {
  SWIG_DExceptionCodes code;
  SWIG_DExceptionCallback_t callback;
} SWIG_DException_t;

static SWIG_DException_t SWIG_d_exceptions[] = {
  { SWIG_DException, NULL },
  { SWIG_DIllegalArgumentException, NULL },
  { SWIG_DIllegalElementException, NULL },
  { SWIG_DIOException, NULL },
  { SWIG_DNoSuchElementException, NULL }
};

static void SWIGUNUSED SWIG_DSetPendingException(SWIG_DExceptionCodes code, const char *msg) {
  if ((size_t)code < sizeof(SWIG_d_exceptions)/sizeof(SWIG_DException_t)) {
    SWIG_d_exceptions[code].callback(msg);
  } else {
    SWIG_d_exceptions[SWIG_DException].callback(msg);
  }
}

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGRegisterExceptionCallbacks_taglib(
  SWIG_DExceptionCallback_t exceptionCallback,
  SWIG_DExceptionCallback_t illegalArgumentCallback,
  SWIG_DExceptionCallback_t illegalElementCallback,
  SWIG_DExceptionCallback_t ioCallback,
  SWIG_DExceptionCallback_t noSuchElementCallback) {
  SWIG_d_exceptions[SWIG_DException].callback = exceptionCallback;
  SWIG_d_exceptions[SWIG_DIllegalArgumentException].callback = illegalArgumentCallback;
  SWIG_d_exceptions[SWIG_DIllegalElementException].callback = illegalElementCallback;
  SWIG_d_exceptions[SWIG_DIOException].callback = ioCallback;
  SWIG_d_exceptions[SWIG_DNoSuchElementException].callback = noSuchElementCallback;
}


// Callback for returning strings to D without leaking memory.
typedef char * (* SWIG_DStringHelperCallback)(const char *);
static SWIG_DStringHelperCallback SWIG_d_string_callback = NULL;

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT void SWIGRegisterStringCallback_taglib(SWIG_DStringHelperCallback callback) {
  SWIG_d_string_callback = callback;
}


/* Contract support. */
#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_DSetPendingException(SWIG_DException, msg); return nullreturn; } else


  #include "tag.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void D_delete_Tag(void * jarg1) {
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  
  arg1 = (TagLib::Tag *)jarg1;
  delete arg1;
}


SWIGEXPORT void * D_Tag_title(void * jarg1) {
  void * jresult ;
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  String result;
  
  arg1 = (TagLib::Tag *)jarg1;
  result = ((TagLib::Tag const *)arg1)->title();
  jresult = new String((const String &)result); 
  return jresult;
}


SWIGEXPORT void * D_Tag_artist(void * jarg1) {
  void * jresult ;
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  String result;
  
  arg1 = (TagLib::Tag *)jarg1;
  result = ((TagLib::Tag const *)arg1)->artist();
  jresult = new String((const String &)result); 
  return jresult;
}


SWIGEXPORT void * D_Tag_album(void * jarg1) {
  void * jresult ;
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  String result;
  
  arg1 = (TagLib::Tag *)jarg1;
  result = ((TagLib::Tag const *)arg1)->album();
  jresult = new String((const String &)result); 
  return jresult;
}


SWIGEXPORT void * D_Tag_comment(void * jarg1) {
  void * jresult ;
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  String result;
  
  arg1 = (TagLib::Tag *)jarg1;
  result = ((TagLib::Tag const *)arg1)->comment();
  jresult = new String((const String &)result); 
  return jresult;
}


SWIGEXPORT void * D_Tag_genre(void * jarg1) {
  void * jresult ;
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  String result;
  
  arg1 = (TagLib::Tag *)jarg1;
  result = ((TagLib::Tag const *)arg1)->genre();
  jresult = new String((const String &)result); 
  return jresult;
}


SWIGEXPORT void * D_Tag_year(void * jarg1) {
  void * jresult ;
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  uint result;
  
  arg1 = (TagLib::Tag *)jarg1;
  result = ((TagLib::Tag const *)arg1)->year();
  jresult = new uint((const uint &)result); 
  return jresult;
}


SWIGEXPORT void * D_Tag_track(void * jarg1) {
  void * jresult ;
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  uint result;
  
  arg1 = (TagLib::Tag *)jarg1;
  result = ((TagLib::Tag const *)arg1)->track();
  jresult = new uint((const uint &)result); 
  return jresult;
}


SWIGEXPORT void D_Tag_setTitle(void * jarg1, void * jarg2) {
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  String *arg2 = 0 ;
  
  arg1 = (TagLib::Tag *)jarg1;
  arg2 = (String *)jarg2;
  if (!arg2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "String const & type is null");
    return ;
  } 
  (arg1)->setTitle((String const &)*arg2);
}


SWIGEXPORT void D_Tag_setArtist(void * jarg1, void * jarg2) {
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  String *arg2 = 0 ;
  
  arg1 = (TagLib::Tag *)jarg1;
  arg2 = (String *)jarg2;
  if (!arg2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "String const & type is null");
    return ;
  } 
  (arg1)->setArtist((String const &)*arg2);
}


SWIGEXPORT void D_Tag_setAlbum(void * jarg1, void * jarg2) {
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  String *arg2 = 0 ;
  
  arg1 = (TagLib::Tag *)jarg1;
  arg2 = (String *)jarg2;
  if (!arg2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "String const & type is null");
    return ;
  } 
  (arg1)->setAlbum((String const &)*arg2);
}


SWIGEXPORT void D_Tag_setComment(void * jarg1, void * jarg2) {
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  String *arg2 = 0 ;
  
  arg1 = (TagLib::Tag *)jarg1;
  arg2 = (String *)jarg2;
  if (!arg2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "String const & type is null");
    return ;
  } 
  (arg1)->setComment((String const &)*arg2);
}


SWIGEXPORT void D_Tag_setGenre(void * jarg1, void * jarg2) {
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  String *arg2 = 0 ;
  
  arg1 = (TagLib::Tag *)jarg1;
  arg2 = (String *)jarg2;
  if (!arg2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "String const & type is null");
    return ;
  } 
  (arg1)->setGenre((String const &)*arg2);
}


SWIGEXPORT void D_Tag_setYear(void * jarg1, void * jarg2) {
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  uint arg2 ;
  uint *argp2 ;
  
  arg1 = (TagLib::Tag *)jarg1;
  argp2 = (uint *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null uint");
    return ;
  }
  arg2 = *argp2; 
  (arg1)->setYear(arg2);
}


SWIGEXPORT void D_Tag_setTrack(void * jarg1, void * jarg2) {
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  uint arg2 ;
  uint *argp2 ;
  
  arg1 = (TagLib::Tag *)jarg1;
  argp2 = (uint *)jarg2;
  if (!argp2) {
    SWIG_DSetPendingException(SWIG_DIllegalArgumentException, "Attempt to dereference null uint");
    return ;
  }
  arg2 = *argp2; 
  (arg1)->setTrack(arg2);
}


SWIGEXPORT unsigned int D_Tag_isEmpty(void * jarg1) {
  unsigned int jresult ;
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  bool result;
  
  arg1 = (TagLib::Tag *)jarg1;
  result = (bool)((TagLib::Tag const *)arg1)->isEmpty();
  jresult = result;
  return jresult;
}


SWIGEXPORT void D_Tag_duplicate__SWIG_0(void * jarg1, void * jarg2, unsigned int jarg3) {
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  TagLib::Tag *arg2 = (TagLib::Tag *) 0 ;
  bool arg3 ;
  
  arg1 = (TagLib::Tag *)jarg1;
  arg2 = (TagLib::Tag *)jarg2;
  arg3 = jarg3 ? true : false;
  TagLib::Tag::duplicate((TagLib::Tag const *)arg1,arg2,arg3);
}


SWIGEXPORT void D_Tag_duplicate__SWIG_1(void * jarg1, void * jarg2) {
  TagLib::Tag *arg1 = (TagLib::Tag *) 0 ;
  TagLib::Tag *arg2 = (TagLib::Tag *) 0 ;
  
  arg1 = (TagLib::Tag *)jarg1;
  arg2 = (TagLib::Tag *)jarg2;
  TagLib::Tag::duplicate((TagLib::Tag const *)arg1,arg2);
}


#ifdef __cplusplus
}
#endif

